---
  - name: EC2 instance provisioning
    hosts: local
    connection: local
    gather_facts: False
    vars:
      instance_type: t2.micro
      security_group: default
      image: ami-c998b6b2
      keypair: tulasi_cloudops
      region: us-east-1
      count: 1
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 10
          delete_on_termination: true 
    tasks:
      - name: Create security group
        ec2_group:
          name: "test_security_group"
          description: "test security group"
          region: "{{ region }}"
          rules:
           - proto: tcp  # ssh
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp  # https
             from_port: 443
             to_port: 443
             cidr_ip: 0.0.0.0/0
          rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0
        register: test_firewall
      - name: Launch the new EC2 Instance
        local_action: ec2
                      instance_type={{ instance_type}}
                      image={{ image }}
                      instance_tags='{"Name":"test-instance-1"}'
                      volumes={{ volumes }}
                      wait=true
                      region={{ region }}
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2
      - name: Wait for SSH to come up
        local_action: wait_for
                      host={{item.public_ip}}
                      port=22
                      state=started
        with_items: "{{ec2.instances}}"
